language: node_js # 设置语言
  
  node_js: stable # 设置相应版本
  
  cache:
      apt: true
      directories:
          - node_modules # 设置缓存，传说会在构建的时候快一些
  
  before_install:
      - npm install hexo-cli -g
      - npm install gulp-htmlclean gulp-htmlmin gulp-uglify gulp-minify-css --save
  install:
      - npm install # 安装hexo及插件

  
  script:
      - hexo clean # 清除
      - hexo generate && gulp
  
  after_script:
      - git clone ${GH_REF} pub_web # 将发布服务的仓库clone下来，
      - cp -rf public/* pub_web/ # 将源博客仓库目录下的public文件夹下的文件复制到发布服务的仓库中
      - cd pub_web # 进入到git仓库
      - git config user.name "username"
      - git config user.email "username@mail.com"
      - git add .
      - git commit -am "Travis CI Auto Builder :$(date '+%Y-%m-%d %H:%M:%S' -d '+8 hour')" # 零时区，+8小时
      - git push origin master 
  branches:
      only:
          - source #只监测master分支
  env:
      global:
          - GH_REF: https://chuxinshuo:${GITHUB_TOKEN}@github.com/chuxinshuo/chuxinshuo.github.io #设置GH_REF


