language: node_js
node_js:
- 8.9.0
cache:
  directories:
  - node_modules
before_install:
- export TZ='Asia/Shanghai'
- npm install hexo-cli -g
install:
- npm install
script:
- hexo clean
- hexo generate && gulp
after_script:
  - cd ./public
  - git init
  - git config user.name "chuxinshuo"
  - git config user.email "kafeiyucha@126.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  # Github Pages
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master 
  # Coding Pages
  - git push --force --quiet "https://simyong:${CODING_TOKEN}@${CO_REF}" master:master

branches:
  only:
  - source  

env:
 global:
   # Github Pages
   - GH_REF: github.com/chuxinshuo/chuxinshuo.github.io.git  
   # Coding Pages
   - CO_REF: git.dev.tencent.com/simyong/simyong.coding.me.git
